<?php

//
//Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 
// and 
//, the first 
// terms will be:
//     123581321345589
//By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.



$previous = 0;
$current = 1;
$sum = 0;

while ($previous < 4000000) {
    $next = $previous + $current;
    if ($next % 2 == 0) {
        $sum += $next;
    }
    
    $previous = $current;
    $current = $next;
}

